### ISSUE TITLE
Can't undo clicking errors under "Is this prediction correct?" and "flag this player as a bot?" (Different from my last question)

### ISSUE THREAD

**Issue by ltmetalman** [Bot-detector/bot-detector#129] opened 2021-06-18 06:31 UTC
I don't mean to spam issues and complaints and then not be able to respond, but I've been mining a star with one guy, and I agreed with the prediction that he is a real player, but for flag this player as a bot I accidentally pressed Yes... = medical issue, my fault nonetheless.

Do I have a setting wrong that makes it impossible to edit the decision? I have send names set to every 5 minutes, so I would have thought I had that much time at least
![c2](https://user-images.githubusercontent.com/54198179/122516735-c03a6180-cfd4-11eb-9faf-0dc538c432d1.JPG)
![c3](https://user-images.githubusercontent.com/54198179/122516737-c03a6180-cfd4-11eb-8f90-176837f091fa.JPG)
![c1](https://user-images.githubusercontent.com/54198179/122516738-c0d2f800-cfd4-11eb-80cb-f1540b46e282.JPG)

I don't want to mess up your system with false and useless tags, so I hope this can help with something, anything to get rid of bots mining on top of me in motherload mine, and just screwing up the market..

**Comment by Ferrariic** [comment] 2021-06-18 06:38
Hey there! No worries I can flip the flag on our end :) You may have to relog to send another prediction for the same account through. We evaluate the feedback as a measure of how well the system is performing, and if there are any notable spots of weakness. So this minor flip wouldn't be bad at all for the process.

**Comment by ltmetalman** [comment] 2021-06-18 07:00
Oh, cool. TY.
For future reference, how do I relog? Do I have to restart runelite and search the name again? Also, does your group have measures in place to stop people from messing up your system? The same way that people messed up cleverbot by training it to curse at people? I'm sure this plugin isn't great for the botting business.

**Comment by Cyborger1** [comment] 2021-06-18 14:39
The flag and feedback are sent immediately upon clicking the buttons. There's no way to undo what you sent from the plugin side. If you log out and log back in, the remembered feedbacks and flags on the plugin are cleared, allowing you to send another feedback again.

Closing this as it's not a bug or something that we intend to change.

**Closed by Cyborger1** 2021-06-18 14:39 UTC
Labels: won't fix
